# Copyright (c) 2023 - now int32top
# Built upon MkDocs & Material for MkDocs

# Project information
site_name: int32top
site_url: https://localhost:8000/ # build and run on server, to visit it, type in the server's IP address and port number like this: xxx.xxx.xxx.xxx:8000
site_author: int32top
site_description: >-
  Welcome to int32 top. This site serves as a personal knowledge base for me to record my thoughts and ideas. 
  It is also a place for me to share my knowledge and experience with the world. 
  I hope you find something useful here.

# Repository
repo_name: ppea.github.io
repo_url: https://github.com/ppea/ppea.github.io

# Copyright
copyright: Copyright &copy; 2021 ~ now | int32top

# Configuration
theme:
  custom_dir: material/overrides
  name: material
  logo: static/images/logo.png
  language: en
  features:
    - announce.dismiss
    # - content.action.edit
    # - content.action.view
    - content.code.annotate
    # - content.code.copy
    # - content.code.select
    # - content.tabs.link
    # - content.tooltips
    - header.autohide
    # - navigation.expand # expand the side navigation bar by default
    # - navigation.footer
    # - navigation.indexes # documents can be directly attached to sections, which is particularly useful for providing overview pages
    # - navigation.instant
    # - navigation.instant.prefetch # for large file
    # - navigation.instant.progress # loading progress bar
    # - navigation.path # breadcrumb path on top of page
    # - navigation.prune # only build the visible part of the navigation tree
    # - navigation.sections # navigation - top level will render as sections
    # - navigation.tabs
    # - navigation.tabs.sticky # tabs stick to the top of the page
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate # toc is merged into the left navigation bar
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  font:
    text: Roboto Slab
    code: Roboto Mono
  favicon: static/images/logo.png
  icon:
    logo: logo
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    tag:
      default-tag: fontawesome/solid/tag
      hardware-tag: fontawesome/solid/microchip
      software-tag: fontawesome/solid/laptop-code

# Plugins
plugins:
  - tags
  # - social
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  # - privacy
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: 简体中文
          build: true
          site_name: int32.top
          nav_translations: # note that all titles and subtitles in the navigation bar that need to be translated can be put here, but with no indentation
            INDEX: 首页
            ABOUT: 关于
            01.MATH: 01.数学
            ANALYSIS: 分析
            ALGEBRA: 代数
            PROBABILITY-STATISTICS: 概率与统计
            COMPLEX-VARIABLE-FUNCTIONS: 复变函数
            DIFFERENTIAL-EQUATION: 微分方程
            OPTIMIZATION : 最优化 
            DISCRETE-MATH: 离散数学
            INFORMATION-THEORY : 信息论 
            NUMERICAL-ANALYSIS: 数值分析
            GAME-THEORY : 博弈论  
            GEOMETRY-GRAPHICS: 几何与图形学
            # COMPUTER-GRAPHICS-FROM-SCRATCH: 计算机图形学从零开始
            02.CS: 02.计算机科学
            THE-MISSING-SEMESTER : 计算机必学工具 
            COMPUTER-SYSTEM: 计算机系统
            OS: 操作系统
            DATA-BASE : 数据库 
            NETWORK: 计算机网络
            DATA-STRUCTURE-ALGO: 数据结构与算法
            COMPILER-THEORY: 编译原理
            SOFTWARE-ENGINEERING: 软件工程
            PARALLEL-COMPUTING: 并行计算
            DISTRIBUTED-SYSTEM: 分布式系统
            03.CODING: 03.编程
            CODING-ENV: 编程环境
            COMMAND-LINE: 命令行
            SHELL: 终端解释器SHELL
            ROOKIE 🏆: 编程新手村 🏆
            C/C++ : C/C++ 
            C: C
            C-NOTES: C笔记
            C++: C++
            C++-NOTES: C++笔记
            MAKE-SERIES: MAKE系列
            PYTHON: PYTHON
            ROADMAP: 路线图
            HTML/CSS/JS: HTML/CSS/JS
            HTML: 超文本标记语言
            CSS: 级联样式表
            JAVASCRIPT: JAVASCRIPT
            WEB-DEV: 浏览器端开发
            DATABASE : 数据库 
            RDBMS: 关系型数据库管理系统
            NOSQL: 非关系型数据库
            TSDB: 时序数据库
            GRAPHDB: 图数据库
            04.EMBEDDED: 04.嵌入式系统
            THEORY: 理论
            ELECTRONICS: 电子学
            CIRCUITS: 电路
            SIGNAL-SYSTEM: 信号与系统
            FREERTOS: 实时操作系统
            LINUX: LINUX
            BASICS : 基础 
            EMBED-BASICS: 嵌入式基础
            JUST: 江协科技
            YOUNGTALK: 洋桃科技
            ALIENTEK: 正点原子
            DIGIKEY: 德捷电子
            REFERENCE: 参考链接
            SIMULATION: 仿真
            DEVKIT : 开发板 
            ARDUINO: ARDUINO
            STM32: 意法半导体STM32
            STM32H743IIT: STM32H743IIT
            STM32MP157: STM32MP157
            STM32-NOTES: STM32学习笔记
            MCU-STM32H743IIT: MCU-STM32H743IIT
            MPU-STM32MP157: MPU-STM32MP157
            ESP32: 乐鑫ESP32
            RASPBERRYPI: 树莓派
            JETSON: 英伟达JETSON
            IDE : 集成开发环境 
            MYSETUP : 我的工具链 
            KEIL : KEIL 
            OFFICIAL-GUIDE-MDK4: MDK4官方指南
            OFFICIAL-GUIDE-MDK5: MDK5官方指南
            PREFACE: 前言
            MDK-INTRODUCTION: MDK简介
            CMSIS: CMSIS库
            SOFTWARE-COMPONENTS: 软件组件
            CREATE-APP: 创建应用
            DEBUG-APP: 调试应用
            MDK-MIDDLEWARE: MDK中间件
            PLATFORMIO: PLATFORMIO
            DEV-FRAMEWORK: 开发框架
            CMSIS : Cortex微控制器软件接口标准 
            ESP-IDF: 乐鑫物联网开发框架(ESP-IDF)
            USEFUL-LIB : 常用嵌入式开发库 
            05.DSP: 05.数字信号处理
            NOTE-DSP-STUFF : “DSP相关内容”笔记 
            TIME-FREQ-ANA : 时频分析      
            06.IOT: 06.物联网
            WSN : 无线传感器网络 
            MQTT: 消息队列遥测传输协议
            BROKER: 代理
            CLIENT: 客户端
            07.MN: 07.移动通信
            08.CLOUD: 08.云
            CLOUD-TECH : 云技术 
            HANDS-ON : 上手实践 
            Have A Server: 拥有一台服务器
            Server Configuration: 服务器配置
            Get A Domain Name: 获得一个域名
            09.AI: 09.人工智能
            BASICS : 基础 
            FRAMEWORKS : 框架 
            GAUSSIAN-PROCESS : 高斯过程 
            LNN: 线性神经网络
            MLP: 多层感知机
            CNN: 卷积神经网络
            RNN: 循环神经网络
            TRANSFORMER: “变形金刚”
            GNN : 图神经网络 
            GAN: 生成对抗网络
            RL : 强化学习 
            LHY-RL: 李宏毅强化学习
            EASY-RL: 蘑菇书强化学习 
            RL Basics: 强化学习基础
            Markov Decision Process (MDP): 马尔可夫决策过程 (MDP)
            Q Table Methods (Q-Learning): Q表方法(Q学习)
            Policy Gradient Methods (PG): 策略梯度方法 (PG)
            Proximal Policy Optimization (PPO): 近端策略优化 (PPO)
            Deep Q-Network (DQN): 深度Q网络 (DQN)
            DQN Advanced: DQN进阶
            DQN Continuous Action: DQN连续动作
            Actor-Critic Method (AC): 演员-评论家方法 (AC)
            Sparse Rewards: 稀疏奖励
            Imitation Learning: 模仿学习
            Deep Deterministic Policy Gradient (DDPG): 深度确定性策略梯度 (DDPG)
            AlphaStar: AlphaStar算法
            FL : 联邦学习 
            MULTI-AGENT : 多智能体 
            TL : 迁移学习 
            NLP: 自然语言处理
            CV : 计算机视觉 
            NOTE-D2L : 动手学深度学习 
            CH1-INTRO: CH1-引言
            CH2-PRE: CH2-预备知识
            CH3-LNN : CH3-线性神经网络 
            CH4-MLP : CH4-多层感知机 
            CH5-DL-COMPUTING: CH5-深度学习计算
            CH6-CNN: CH6-卷积神经网络
            CH7-MODERN-CNN: CH7-现代卷积神经网络
            SHM: 结构健康监测
            STRUCTURAL-DYNAMICS : 结构动力学 
            RESPONSE-CALCULATION: 响应计算
            NSEL-REPORT: NSEL报告
            10.ROBOT: 10.机器人
            CONTROL: 控制
            ROS : 机器人操作系统 
            OFFICIAL-GUIDE: 官方指南
            INSTALLATION: 安装
            DISTRIBUTION: 发行版
            TUTORIALS: 教程
            CLI-TOOLS: 命令行工具
            CLIENT-LIBRARIES: 客户端库
            HANDSON-ROS: 动手学ROS
            P1-GET-STARTED: P1-入门
            VISUALIZATION: 可视化    
            WEB-BASED: WEB端
            CLIENT-BASED: 客户端
            97.FAVORITES: 97.收藏夹
            98.DEV: 98.开发
            DEVENV: 开发环境
            EMBEDDED-DEV: 嵌入式开发 
            99.PROJECT: 99.项目
# # Hooks
# hooks:
#   - material/overrides/hooks/shortcodes.py
#   - material/overrides/hooks/translations.py 

# Additional configuration 
extra:
  # generator: false
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
    # property: GOOGLE_ANALYTICS_KEY
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  # alternate:
  #   - name: English
  #     link: /en/ 
  #     lang: en
  #   - name: Chinese
  #     link: /zh/
  #     lang: zh
  social:
    - icon: fontawesome/solid/house
      link: https://ppea.github.io
    - icon: fontawesome/brands/github
      link: https://github.com/ppea
  tags:
    Default: default-tag
    Hardware: hardware-tag
    Software: software-tag
  # consent:
  #   title: Cookie consent
  #   description: >- 
  #     We use cookies to recognize your repeated visits and preferences, as well
  #     as to measure the effectiveness of our documentation and whether users
  #     find what they're searching for. With your consent, you're helping us to
  #     make our documentation better.

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
